[workspace]

members = ["crates/*"]
resolver = "2"

[workspace.package]
name = "mrot"
version = "0.1.0"
edition = "2021"
rust-version = "1.84"
authors = ["Sven Siegmund <sven.siegmund@gmail.com>"]
description = "Meal rotator"
repository = "https://github.com/fleetingbytes/mrot/"
license-file = "BSD-2-Clause"
keywords = ["tools", "tracking", "meal", "cooking", "calendar"]
categories = ["command-line-utilities"]

[workspace.lints.rust]
missing_docs = "deny"

[workspace.lints.clippy]
